### ISSUE TITLE
Add feature to disable egui builtin fonts

### ISSUE THREAD

**Issue by iTitus** [mvlabat/bevy_egui#107]
I would like to disable the builtin egui fonts to save space.
egui includes a feature in its default feature set that includes them.
bevy_egui should mirror that with a default feature that pulls in that egui feature that can be disabled.
```toml
[features]
default = ["manage_clipboard", "open_url", "default_fonts"]
immutable_ctx = []
manage_clipboard = ["arboard", "thread_local"]
open_url = ["webbrowser"]
default_fonts = ["egui/default_fonts"]

[dependencies]
bevy = { version = "0.7", default-features = false, features = ["bevy_render", "bevy_core_pipeline"] }
egui = { version = "0.18", default-features = false, features = ["bytemuck"] }
```
