### ISSUE TITLE
Clicks not recogniced on Android

### ISSUE THREAD

**Issue by michaelrampl** [mvlabat/bevy_egui#134]
The following "on update system" works well on desktop. Unfortunately, on mobile I cannot get it working properly. It seems like clicks/taps are not recognized so even I create other elements such as sliders, dropdowns, ... and try to tap them, nothing happens.

```rs
fn update_menu(mut egui_context: ResMut<EguiContext>) {
    egui::containers::Area::new("main_container").show(egui_context.ctx_mut(), |ui| {
    ui.button("click me");
...
```

These are my dependencies
```toml
[dependencies.bevy]
version = "0.9.0"
default-features = false
features = [
  "render",
  "bevy_asset",
  "png",
  "x11"
]

[dependencies.bevy_egui]
version = "0.17.1"
default-features = false
features = [
  "default_fonts"
]
```

As far as I have seen in https://github.com/rust-windowing/android-ndk-rs, egui should work on android so what am I missing here? (I'm using `cargo apk` to build the android package)
