### ISSUE TITLE
arboard fails to build for android target (and probably iOS)

### ISSUE THREAD

**Issue by jsclary** [mvlabat/bevy_egui#198]
Obviously, if *bevy_egui* is a direct dependency, you can work around this with:
```toml
[dependencies]
bevy_egui = { version = "0.21.0", default-features = false, features = ["open_url", "default_fonts"] }
```
However, if you are targeting multiple platforms, it gets more complicated:
```toml
[target.'cfg(target_os = "android")'.dependencies]
bevy_egui = { version = "0.21.0", default-features = false, features = ["open_url", "default_fonts"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
bevy_egui = { version = "0.21.0"  }
```
And, if it happens to be a dependency of third party plugins you use (such as bevy_console) and isn't feature-controlled there, I think you are just out of luck unless you're prepared to fork all of those projects.

Given that there's already an explicit exclusion for wasm, it seems reasonable to extend it to something like:
```toml
[target.'cfg(not(any(target_arch = "wasm32", target_os = "android", target_os = "ios")))'.dependencies]
arboard = { version = "3.2.0", optional = true }
thread_local = { version = "1.1.0", optional = true }
```

I would guess the same is true of iOS so I stuck that condition in as well but I don't have a Mac to test with and I haven't forked bevy_egui so that last block is entirely untested.

Though, really, it'd be nice to have clipboard support on Android (and iOS) at some point. It's not something I have the time or expertise to take on at the moment but maybe in the future.
