### ISSUE TITLE
Compile errors when building to WASM target

### ISSUE THREAD

**Issue by inflectrix** [mvlabat/bevy_egui#269]
I'm not sure how this is happening or how this is reproducible, but I have the following in my Cargo.toml:
```toml
[features]
default = []
debug = ["dep:bevy-inspector-egui", "bevy_rapier3d/debug-render"]
editor = ["dep:bevy_editor_pls"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.13.0"
bevy-inspector-egui = { version = "0.23.3", optional = true }
bevy_editor_pls = { version = "0.8.1", optional = true }
bevy_egui = "0.26.0"
bevy_fps_controller = "0.2.5"
bevy_hanabi = "0.10.0"
bevy_rapier3d = "0.25.0"

[[bin]]
name = "editor"
required-features = ["editor"]
```

Compiling with `cargo build --target wasm32-unknown-unknown` produces the following errors:

```
error[E0412]: cannot find type `ClipboardEvent` in crate `web_sys`
   --> /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_egui-0.26.0/src/web_clipboard.rs:105:41
    |
105 |     closure: Closure<dyn FnMut(web_sys::ClipboardEvent)>,
    |                                         ^^^^^^^^^^^^^^ help: a struct with a similar name exists: `KeyboardEvent`
    |
   ::: /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.67/src/features/gen_KeyboardEvent.rs:5:1
    |
5   | #[wasm_bindgen]
    | --------------- similarly named struct `KeyboardEvent` defined here

error[E0412]: cannot find type `ClipboardEvent` in crate `web_sys`
   --> /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_egui-0.26.0/src/web_clipboard.rs:118:71
    |
118 |     let closure = Closure::<dyn FnMut(_)>::new(move |_event: web_sys::ClipboardEvent| {
    |                                                                       ^^^^^^^^^^^^^^ help: a struct with a similar name exists: `KeyboardEvent`
    |
   ::: /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.67/src/features/gen_KeyboardEvent.rs:5:1
    |
5   | #[wasm_bindgen]
    | --------------- similarly named struct `KeyboardEvent` defined here

error[E0412]: cannot find type `ClipboardEvent` in crate `web_sys`
   --> /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_egui-0.26.0/src/web_clipboard.rs:152:71
    |
152 |     let closure = Closure::<dyn FnMut(_)>::new(move |_event: web_sys::ClipboardEvent| {
    |                                                                       ^^^^^^^^^^^^^^ help: a struct with a similar name exists: `KeyboardEvent`
    |
   ::: /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.67/src/features/gen_KeyboardEvent.rs:5:1
    |
5   | #[wasm_bindgen]
    | --------------- similarly named struct `KeyboardEvent` defined here

error[E0412]: cannot find type `ClipboardEvent` in crate `web_sys`
   --> /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_egui-0.26.0/src/web_clipboard.rs:186:70
    |
186 |     let closure = Closure::<dyn FnMut(_)>::new(move |event: web_sys::ClipboardEvent| {
    |                                                                      ^^^^^^^^^^^^^^ help: a struct with a similar name exists: `KeyboardEvent`
    |
   ::: /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.67/src/features/gen_KeyboardEvent.rs:5:1
    |
5   | #[wasm_bindgen]
    | --------------- similarly named struct `KeyboardEvent` defined here

error[E0599]: no method named `clipboard` found for struct `Navigator` in the current scope
   --> /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_egui-0.26.0/src/web_clipboard.rs:233:35
    |
233 |         let Some(clipboard) = nav.clipboard() else {
    |                                   ^^^^^^^^^ method not found in `Navigator`

Some errors have detailed explanations: E0412, E0599.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `bevy_egui` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
```

This is happening in a GitHub Codespace on Rust 1.76.0
